- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
    MYSQL_PASSWORD: ExpenseApp@1
    MYSQL-SERVER-IPADDRES:  "{{MYSQL_HOST}}"
  tasks:
  - name: install mysql
    package:
      name: mysql-server
      state: present
    
  - name: setting root MYSQL_PASSWORD
    command: mysql_secure_installation --set-root-pass {{ MYSQL_PASSWORD }}
  - name: load schema
    ansible.mysql.mysql_db:
      name: all
      state: import
      target: /app/schema/backend.sql
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: "{{ MYSQL_PASSWORD }}"

  - name: enable and start mysqld
    service:
      name: mysqld
      state: started
      enabled: yes
    

    