- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    package:
      name: mysql-server
      state: present
    
  - name: setting root MYSQL_PASSWORD
    command: mysql_secure_installation --set-root-pass ExpenseApp@1
  - name: load schema
    ansible.mysql.mysql_db:
      name: all
      state: import
      target: /app/schema/backend.sql
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: ExpenseApp@1

  - name: enable and start mysqld
    service:
      name: mysqld
      state: started
      enabled: yes
    

    